/*
Sumo Logic API

Go client for Sumo Logic API. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologic

import (
	"encoding/json"
)

// checks if the CSEWindowsStorageLimitExceededTrackerAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CSEWindowsStorageLimitExceededTrackerAllOf{}

// CSEWindowsStorageLimitExceededTrackerAllOf struct for CSEWindowsStorageLimitExceededTrackerAllOf
type CSEWindowsStorageLimitExceededTrackerAllOf struct {
	// The sensor ID.
	SensorId *string `json:"sensorId,omitempty"`
	// The sensor's hostname.
	SensorHostname *string `json:"sensorHostname,omitempty"`
	// The path of the folder.
	FolderPath *string `json:"folderPath,omitempty"`
	// The complete file path.
	FolderSizeLimit *string `json:"folderSizeLimit,omitempty"`
	// Current size of the folder.
	CurrentFolderSize *string `json:"currentFolderSize,omitempty"`
	// The percentage available disk space limit.
	PercentageAvailableDiskSpaceLimit *string `json:"percentageAvailableDiskSpaceLimit,omitempty"`
	// The current percentage available disk space.
	CurrentPercentageAvailableDiskSpace *string `json:"currentPercentageAvailableDiskSpace,omitempty"`
	// The last error.
	LastError *string `json:"lastError,omitempty"`
}

// NewCSEWindowsStorageLimitExceededTrackerAllOf instantiates a new CSEWindowsStorageLimitExceededTrackerAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCSEWindowsStorageLimitExceededTrackerAllOf() *CSEWindowsStorageLimitExceededTrackerAllOf {
	this := CSEWindowsStorageLimitExceededTrackerAllOf{}
	return &this
}

// NewCSEWindowsStorageLimitExceededTrackerAllOfWithDefaults instantiates a new CSEWindowsStorageLimitExceededTrackerAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCSEWindowsStorageLimitExceededTrackerAllOfWithDefaults() *CSEWindowsStorageLimitExceededTrackerAllOf {
	this := CSEWindowsStorageLimitExceededTrackerAllOf{}
	return &this
}

// GetSensorId returns the SensorId field value if set, zero value otherwise.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetSensorId() string {
	if o == nil || IsNil(o.SensorId) {
		var ret string
		return ret
	}
	return *o.SensorId
}

// GetSensorIdOk returns a tuple with the SensorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetSensorIdOk() (*string, bool) {
	if o == nil || IsNil(o.SensorId) {
		return nil, false
	}
	return o.SensorId, true
}

// HasSensorId returns a boolean if a field has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) HasSensorId() bool {
	if o != nil && !IsNil(o.SensorId) {
		return true
	}

	return false
}

// SetSensorId gets a reference to the given string and assigns it to the SensorId field.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) SetSensorId(v string) {
	o.SensorId = &v
}

// GetSensorHostname returns the SensorHostname field value if set, zero value otherwise.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetSensorHostname() string {
	if o == nil || IsNil(o.SensorHostname) {
		var ret string
		return ret
	}
	return *o.SensorHostname
}

// GetSensorHostnameOk returns a tuple with the SensorHostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetSensorHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.SensorHostname) {
		return nil, false
	}
	return o.SensorHostname, true
}

// HasSensorHostname returns a boolean if a field has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) HasSensorHostname() bool {
	if o != nil && !IsNil(o.SensorHostname) {
		return true
	}

	return false
}

// SetSensorHostname gets a reference to the given string and assigns it to the SensorHostname field.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) SetSensorHostname(v string) {
	o.SensorHostname = &v
}

// GetFolderPath returns the FolderPath field value if set, zero value otherwise.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetFolderPath() string {
	if o == nil || IsNil(o.FolderPath) {
		var ret string
		return ret
	}
	return *o.FolderPath
}

// GetFolderPathOk returns a tuple with the FolderPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetFolderPathOk() (*string, bool) {
	if o == nil || IsNil(o.FolderPath) {
		return nil, false
	}
	return o.FolderPath, true
}

// HasFolderPath returns a boolean if a field has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) HasFolderPath() bool {
	if o != nil && !IsNil(o.FolderPath) {
		return true
	}

	return false
}

// SetFolderPath gets a reference to the given string and assigns it to the FolderPath field.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) SetFolderPath(v string) {
	o.FolderPath = &v
}

// GetFolderSizeLimit returns the FolderSizeLimit field value if set, zero value otherwise.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetFolderSizeLimit() string {
	if o == nil || IsNil(o.FolderSizeLimit) {
		var ret string
		return ret
	}
	return *o.FolderSizeLimit
}

// GetFolderSizeLimitOk returns a tuple with the FolderSizeLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetFolderSizeLimitOk() (*string, bool) {
	if o == nil || IsNil(o.FolderSizeLimit) {
		return nil, false
	}
	return o.FolderSizeLimit, true
}

// HasFolderSizeLimit returns a boolean if a field has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) HasFolderSizeLimit() bool {
	if o != nil && !IsNil(o.FolderSizeLimit) {
		return true
	}

	return false
}

// SetFolderSizeLimit gets a reference to the given string and assigns it to the FolderSizeLimit field.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) SetFolderSizeLimit(v string) {
	o.FolderSizeLimit = &v
}

// GetCurrentFolderSize returns the CurrentFolderSize field value if set, zero value otherwise.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetCurrentFolderSize() string {
	if o == nil || IsNil(o.CurrentFolderSize) {
		var ret string
		return ret
	}
	return *o.CurrentFolderSize
}

// GetCurrentFolderSizeOk returns a tuple with the CurrentFolderSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetCurrentFolderSizeOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentFolderSize) {
		return nil, false
	}
	return o.CurrentFolderSize, true
}

// HasCurrentFolderSize returns a boolean if a field has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) HasCurrentFolderSize() bool {
	if o != nil && !IsNil(o.CurrentFolderSize) {
		return true
	}

	return false
}

// SetCurrentFolderSize gets a reference to the given string and assigns it to the CurrentFolderSize field.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) SetCurrentFolderSize(v string) {
	o.CurrentFolderSize = &v
}

// GetPercentageAvailableDiskSpaceLimit returns the PercentageAvailableDiskSpaceLimit field value if set, zero value otherwise.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetPercentageAvailableDiskSpaceLimit() string {
	if o == nil || IsNil(o.PercentageAvailableDiskSpaceLimit) {
		var ret string
		return ret
	}
	return *o.PercentageAvailableDiskSpaceLimit
}

// GetPercentageAvailableDiskSpaceLimitOk returns a tuple with the PercentageAvailableDiskSpaceLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetPercentageAvailableDiskSpaceLimitOk() (*string, bool) {
	if o == nil || IsNil(o.PercentageAvailableDiskSpaceLimit) {
		return nil, false
	}
	return o.PercentageAvailableDiskSpaceLimit, true
}

// HasPercentageAvailableDiskSpaceLimit returns a boolean if a field has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) HasPercentageAvailableDiskSpaceLimit() bool {
	if o != nil && !IsNil(o.PercentageAvailableDiskSpaceLimit) {
		return true
	}

	return false
}

// SetPercentageAvailableDiskSpaceLimit gets a reference to the given string and assigns it to the PercentageAvailableDiskSpaceLimit field.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) SetPercentageAvailableDiskSpaceLimit(v string) {
	o.PercentageAvailableDiskSpaceLimit = &v
}

// GetCurrentPercentageAvailableDiskSpace returns the CurrentPercentageAvailableDiskSpace field value if set, zero value otherwise.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetCurrentPercentageAvailableDiskSpace() string {
	if o == nil || IsNil(o.CurrentPercentageAvailableDiskSpace) {
		var ret string
		return ret
	}
	return *o.CurrentPercentageAvailableDiskSpace
}

// GetCurrentPercentageAvailableDiskSpaceOk returns a tuple with the CurrentPercentageAvailableDiskSpace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetCurrentPercentageAvailableDiskSpaceOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentPercentageAvailableDiskSpace) {
		return nil, false
	}
	return o.CurrentPercentageAvailableDiskSpace, true
}

// HasCurrentPercentageAvailableDiskSpace returns a boolean if a field has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) HasCurrentPercentageAvailableDiskSpace() bool {
	if o != nil && !IsNil(o.CurrentPercentageAvailableDiskSpace) {
		return true
	}

	return false
}

// SetCurrentPercentageAvailableDiskSpace gets a reference to the given string and assigns it to the CurrentPercentageAvailableDiskSpace field.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) SetCurrentPercentageAvailableDiskSpace(v string) {
	o.CurrentPercentageAvailableDiskSpace = &v
}

// GetLastError returns the LastError field value if set, zero value otherwise.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetLastError() string {
	if o == nil || IsNil(o.LastError) {
		var ret string
		return ret
	}
	return *o.LastError
}

// GetLastErrorOk returns a tuple with the LastError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) GetLastErrorOk() (*string, bool) {
	if o == nil || IsNil(o.LastError) {
		return nil, false
	}
	return o.LastError, true
}

// HasLastError returns a boolean if a field has been set.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) HasLastError() bool {
	if o != nil && !IsNil(o.LastError) {
		return true
	}

	return false
}

// SetLastError gets a reference to the given string and assigns it to the LastError field.
func (o *CSEWindowsStorageLimitExceededTrackerAllOf) SetLastError(v string) {
	o.LastError = &v
}

func (o CSEWindowsStorageLimitExceededTrackerAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CSEWindowsStorageLimitExceededTrackerAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SensorId) {
		toSerialize["sensorId"] = o.SensorId
	}
	if !IsNil(o.SensorHostname) {
		toSerialize["sensorHostname"] = o.SensorHostname
	}
	if !IsNil(o.FolderPath) {
		toSerialize["folderPath"] = o.FolderPath
	}
	if !IsNil(o.FolderSizeLimit) {
		toSerialize["folderSizeLimit"] = o.FolderSizeLimit
	}
	if !IsNil(o.CurrentFolderSize) {
		toSerialize["currentFolderSize"] = o.CurrentFolderSize
	}
	if !IsNil(o.PercentageAvailableDiskSpaceLimit) {
		toSerialize["percentageAvailableDiskSpaceLimit"] = o.PercentageAvailableDiskSpaceLimit
	}
	if !IsNil(o.CurrentPercentageAvailableDiskSpace) {
		toSerialize["currentPercentageAvailableDiskSpace"] = o.CurrentPercentageAvailableDiskSpace
	}
	if !IsNil(o.LastError) {
		toSerialize["lastError"] = o.LastError
	}
	return toSerialize, nil
}

type NullableCSEWindowsStorageLimitExceededTrackerAllOf struct {
	value *CSEWindowsStorageLimitExceededTrackerAllOf
	isSet bool
}

func (v NullableCSEWindowsStorageLimitExceededTrackerAllOf) Get() *CSEWindowsStorageLimitExceededTrackerAllOf {
	return v.value
}

func (v *NullableCSEWindowsStorageLimitExceededTrackerAllOf) Set(val *CSEWindowsStorageLimitExceededTrackerAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCSEWindowsStorageLimitExceededTrackerAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCSEWindowsStorageLimitExceededTrackerAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCSEWindowsStorageLimitExceededTrackerAllOf(val *CSEWindowsStorageLimitExceededTrackerAllOf) *NullableCSEWindowsStorageLimitExceededTrackerAllOf {
	return &NullableCSEWindowsStorageLimitExceededTrackerAllOf{value: val, isSet: true}
}

func (v NullableCSEWindowsStorageLimitExceededTrackerAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCSEWindowsStorageLimitExceededTrackerAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


