/*
Sumo Logic API

Go client for Sumo Logic API. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdhocMutingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdhocMutingResponse{}

// AdhocMutingResponse Muting information fields for the monitor.
type AdhocMutingResponse struct {
	// Start time of adhoc muting period in Epoch.
	StartTime int64 `json:"startTime"`
	// End time of the adhoc muting period in Epoch.If muting indefinitely, this will be empty.
	EndTime *int64 `json:"endTime,omitempty"`
}

// NewAdhocMutingResponse instantiates a new AdhocMutingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdhocMutingResponse(startTime int64) *AdhocMutingResponse {
	this := AdhocMutingResponse{}
	this.StartTime = startTime
	return &this
}

// NewAdhocMutingResponseWithDefaults instantiates a new AdhocMutingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdhocMutingResponseWithDefaults() *AdhocMutingResponse {
	this := AdhocMutingResponse{}
	return &this
}

// GetStartTime returns the StartTime field value
func (o *AdhocMutingResponse) GetStartTime() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *AdhocMutingResponse) GetStartTimeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *AdhocMutingResponse) SetStartTime(v int64) {
	o.StartTime = v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *AdhocMutingResponse) GetEndTime() int64 {
	if o == nil || IsNil(o.EndTime) {
		var ret int64
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdhocMutingResponse) GetEndTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.EndTime) {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *AdhocMutingResponse) HasEndTime() bool {
	if o != nil && !IsNil(o.EndTime) {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given int64 and assigns it to the EndTime field.
func (o *AdhocMutingResponse) SetEndTime(v int64) {
	o.EndTime = &v
}

func (o AdhocMutingResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdhocMutingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["startTime"] = o.StartTime
	if !IsNil(o.EndTime) {
		toSerialize["endTime"] = o.EndTime
	}
	return toSerialize, nil
}

type NullableAdhocMutingResponse struct {
	value *AdhocMutingResponse
	isSet bool
}

func (v NullableAdhocMutingResponse) Get() *AdhocMutingResponse {
	return v.value
}

func (v *NullableAdhocMutingResponse) Set(val *AdhocMutingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdhocMutingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdhocMutingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdhocMutingResponse(val *AdhocMutingResponse) *NullableAdhocMutingResponse {
	return &NullableAdhocMutingResponse{value: val, isSet: true}
}

func (v NullableAdhocMutingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdhocMutingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


