/*
Sumo Logic API

Go client for Sumo Logic API. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologic

import (
	"encoding/json"
)

// checks if the BooleanEventAttributeValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BooleanEventAttributeValue{}

// BooleanEventAttributeValue struct for BooleanEventAttributeValue
type BooleanEventAttributeValue struct {
	EventAttributeValue
	Value bool `json:"value"`
}

// NewBooleanEventAttributeValue instantiates a new BooleanEventAttributeValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBooleanEventAttributeValue(value bool, type_ string) *BooleanEventAttributeValue {
	this := BooleanEventAttributeValue{}
	this.Type = type_
	this.Value = value
	return &this
}

// NewBooleanEventAttributeValueWithDefaults instantiates a new BooleanEventAttributeValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBooleanEventAttributeValueWithDefaults() *BooleanEventAttributeValue {
	this := BooleanEventAttributeValue{}
	return &this
}

// GetValue returns the Value field value
func (o *BooleanEventAttributeValue) GetValue() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *BooleanEventAttributeValue) GetValueOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *BooleanEventAttributeValue) SetValue(v bool) {
	o.Value = v
}

func (o BooleanEventAttributeValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BooleanEventAttributeValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedEventAttributeValue, errEventAttributeValue := json.Marshal(o.EventAttributeValue)
	if errEventAttributeValue != nil {
		return map[string]interface{}{}, errEventAttributeValue
	}
	errEventAttributeValue = json.Unmarshal([]byte(serializedEventAttributeValue), &toSerialize)
	if errEventAttributeValue != nil {
		return map[string]interface{}{}, errEventAttributeValue
	}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

type NullableBooleanEventAttributeValue struct {
	value *BooleanEventAttributeValue
	isSet bool
}

func (v NullableBooleanEventAttributeValue) Get() *BooleanEventAttributeValue {
	return v.value
}

func (v *NullableBooleanEventAttributeValue) Set(val *BooleanEventAttributeValue) {
	v.value = val
	v.isSet = true
}

func (v NullableBooleanEventAttributeValue) IsSet() bool {
	return v.isSet
}

func (v *NullableBooleanEventAttributeValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBooleanEventAttributeValue(val *BooleanEventAttributeValue) *NullableBooleanEventAttributeValue {
	return &NullableBooleanEventAttributeValue{value: val, isSet: true}
}

func (v NullableBooleanEventAttributeValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBooleanEventAttributeValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


