/*
Sumo Logic API

Go client for Sumo Logic API. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OTCReceiverNoSpansObservedTrackerAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OTCReceiverNoSpansObservedTrackerAllOf{}

// OTCReceiverNoSpansObservedTrackerAllOf struct for OTCReceiverNoSpansObservedTrackerAllOf
type OTCReceiverNoSpansObservedTrackerAllOf struct {
	// The collector instance ID, e.g. `974b444b-4b45-4f32-aa03-1dbf2a16826d`.
	InstanceId *string `json:"instanceId,omitempty"`
	// The collector instance address, e.g. `172.16.1.14`.
	InstanceAddress *string `json:"instanceAddress,omitempty"`
	// The collector receiver ID, e.g. `otlphttp/2`.
	ReceiverId *string `json:"receiverId,omitempty"`
}

// NewOTCReceiverNoSpansObservedTrackerAllOf instantiates a new OTCReceiverNoSpansObservedTrackerAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOTCReceiverNoSpansObservedTrackerAllOf() *OTCReceiverNoSpansObservedTrackerAllOf {
	this := OTCReceiverNoSpansObservedTrackerAllOf{}
	return &this
}

// NewOTCReceiverNoSpansObservedTrackerAllOfWithDefaults instantiates a new OTCReceiverNoSpansObservedTrackerAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOTCReceiverNoSpansObservedTrackerAllOfWithDefaults() *OTCReceiverNoSpansObservedTrackerAllOf {
	this := OTCReceiverNoSpansObservedTrackerAllOf{}
	return &this
}

// GetInstanceId returns the InstanceId field value if set, zero value otherwise.
func (o *OTCReceiverNoSpansObservedTrackerAllOf) GetInstanceId() string {
	if o == nil || IsNil(o.InstanceId) {
		var ret string
		return ret
	}
	return *o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OTCReceiverNoSpansObservedTrackerAllOf) GetInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceId) {
		return nil, false
	}
	return o.InstanceId, true
}

// HasInstanceId returns a boolean if a field has been set.
func (o *OTCReceiverNoSpansObservedTrackerAllOf) HasInstanceId() bool {
	if o != nil && !IsNil(o.InstanceId) {
		return true
	}

	return false
}

// SetInstanceId gets a reference to the given string and assigns it to the InstanceId field.
func (o *OTCReceiverNoSpansObservedTrackerAllOf) SetInstanceId(v string) {
	o.InstanceId = &v
}

// GetInstanceAddress returns the InstanceAddress field value if set, zero value otherwise.
func (o *OTCReceiverNoSpansObservedTrackerAllOf) GetInstanceAddress() string {
	if o == nil || IsNil(o.InstanceAddress) {
		var ret string
		return ret
	}
	return *o.InstanceAddress
}

// GetInstanceAddressOk returns a tuple with the InstanceAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OTCReceiverNoSpansObservedTrackerAllOf) GetInstanceAddressOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceAddress) {
		return nil, false
	}
	return o.InstanceAddress, true
}

// HasInstanceAddress returns a boolean if a field has been set.
func (o *OTCReceiverNoSpansObservedTrackerAllOf) HasInstanceAddress() bool {
	if o != nil && !IsNil(o.InstanceAddress) {
		return true
	}

	return false
}

// SetInstanceAddress gets a reference to the given string and assigns it to the InstanceAddress field.
func (o *OTCReceiverNoSpansObservedTrackerAllOf) SetInstanceAddress(v string) {
	o.InstanceAddress = &v
}

// GetReceiverId returns the ReceiverId field value if set, zero value otherwise.
func (o *OTCReceiverNoSpansObservedTrackerAllOf) GetReceiverId() string {
	if o == nil || IsNil(o.ReceiverId) {
		var ret string
		return ret
	}
	return *o.ReceiverId
}

// GetReceiverIdOk returns a tuple with the ReceiverId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OTCReceiverNoSpansObservedTrackerAllOf) GetReceiverIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReceiverId) {
		return nil, false
	}
	return o.ReceiverId, true
}

// HasReceiverId returns a boolean if a field has been set.
func (o *OTCReceiverNoSpansObservedTrackerAllOf) HasReceiverId() bool {
	if o != nil && !IsNil(o.ReceiverId) {
		return true
	}

	return false
}

// SetReceiverId gets a reference to the given string and assigns it to the ReceiverId field.
func (o *OTCReceiverNoSpansObservedTrackerAllOf) SetReceiverId(v string) {
	o.ReceiverId = &v
}

func (o OTCReceiverNoSpansObservedTrackerAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OTCReceiverNoSpansObservedTrackerAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstanceId) {
		toSerialize["instanceId"] = o.InstanceId
	}
	if !IsNil(o.InstanceAddress) {
		toSerialize["instanceAddress"] = o.InstanceAddress
	}
	if !IsNil(o.ReceiverId) {
		toSerialize["receiverId"] = o.ReceiverId
	}
	return toSerialize, nil
}

type NullableOTCReceiverNoSpansObservedTrackerAllOf struct {
	value *OTCReceiverNoSpansObservedTrackerAllOf
	isSet bool
}

func (v NullableOTCReceiverNoSpansObservedTrackerAllOf) Get() *OTCReceiverNoSpansObservedTrackerAllOf {
	return v.value
}

func (v *NullableOTCReceiverNoSpansObservedTrackerAllOf) Set(val *OTCReceiverNoSpansObservedTrackerAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableOTCReceiverNoSpansObservedTrackerAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableOTCReceiverNoSpansObservedTrackerAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOTCReceiverNoSpansObservedTrackerAllOf(val *OTCReceiverNoSpansObservedTrackerAllOf) *NullableOTCReceiverNoSpansObservedTrackerAllOf {
	return &NullableOTCReceiverNoSpansObservedTrackerAllOf{value: val, isSet: true}
}

func (v NullableOTCReceiverNoSpansObservedTrackerAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOTCReceiverNoSpansObservedTrackerAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


