/*
Sumo Logic API

Go client for Sumo Logic API. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologic

import (
	"encoding/json"
)

// checks if the ScheduledViewsQuotaUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScheduledViewsQuotaUsage{}

// ScheduledViewsQuotaUsage struct for ScheduledViewsQuotaUsage
type ScheduledViewsQuotaUsage struct {
	// Maximum number of Scheduled Views allowed.
	Quota int32 `json:"quota"`
	// Remaining number of Scheduled Views allowed.
	Remaining int32 `json:"remaining"`
}

// NewScheduledViewsQuotaUsage instantiates a new ScheduledViewsQuotaUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScheduledViewsQuotaUsage(quota int32, remaining int32) *ScheduledViewsQuotaUsage {
	this := ScheduledViewsQuotaUsage{}
	this.Quota = quota
	this.Remaining = remaining
	return &this
}

// NewScheduledViewsQuotaUsageWithDefaults instantiates a new ScheduledViewsQuotaUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScheduledViewsQuotaUsageWithDefaults() *ScheduledViewsQuotaUsage {
	this := ScheduledViewsQuotaUsage{}
	return &this
}

// GetQuota returns the Quota field value
func (o *ScheduledViewsQuotaUsage) GetQuota() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value
// and a boolean to check if the value has been set.
func (o *ScheduledViewsQuotaUsage) GetQuotaOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quota, true
}

// SetQuota sets field value
func (o *ScheduledViewsQuotaUsage) SetQuota(v int32) {
	o.Quota = v
}

// GetRemaining returns the Remaining field value
func (o *ScheduledViewsQuotaUsage) GetRemaining() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Remaining
}

// GetRemainingOk returns a tuple with the Remaining field value
// and a boolean to check if the value has been set.
func (o *ScheduledViewsQuotaUsage) GetRemainingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Remaining, true
}

// SetRemaining sets field value
func (o *ScheduledViewsQuotaUsage) SetRemaining(v int32) {
	o.Remaining = v
}

func (o ScheduledViewsQuotaUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScheduledViewsQuotaUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["quota"] = o.Quota
	toSerialize["remaining"] = o.Remaining
	return toSerialize, nil
}

type NullableScheduledViewsQuotaUsage struct {
	value *ScheduledViewsQuotaUsage
	isSet bool
}

func (v NullableScheduledViewsQuotaUsage) Get() *ScheduledViewsQuotaUsage {
	return v.value
}

func (v *NullableScheduledViewsQuotaUsage) Set(val *ScheduledViewsQuotaUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduledViewsQuotaUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduledViewsQuotaUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduledViewsQuotaUsage(val *ScheduledViewsQuotaUsage) *NullableScheduledViewsQuotaUsage {
	return &NullableScheduledViewsQuotaUsage{value: val, isSet: true}
}

func (v NullableScheduledViewsQuotaUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduledViewsQuotaUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


