/*
Sumo Logic API

Go client for Sumo Logic API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologic

import (
	"encoding/json"
)

// ResolvableTimeRange struct for ResolvableTimeRange
type ResolvableTimeRange struct {
	// Type of the time range. Value must be either `CompleteLiteralTimeRange` or `BeginBoundedTimeRange`.
	Type string `json:"type"`
}

// NewResolvableTimeRange instantiates a new ResolvableTimeRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolvableTimeRange(type_ string) *ResolvableTimeRange {
	this := ResolvableTimeRange{}
	this.Type = type_
	return &this
}

// NewResolvableTimeRangeWithDefaults instantiates a new ResolvableTimeRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolvableTimeRangeWithDefaults() *ResolvableTimeRange {
	this := ResolvableTimeRange{}
	return &this
}

// GetType returns the Type field value
func (o *ResolvableTimeRange) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ResolvableTimeRange) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ResolvableTimeRange) SetType(v string) {
	o.Type = v
}

func (o ResolvableTimeRange) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableResolvableTimeRange struct {
	value *ResolvableTimeRange
	isSet bool
}

func (v NullableResolvableTimeRange) Get() *ResolvableTimeRange {
	return v.value
}

func (v *NullableResolvableTimeRange) Set(val *ResolvableTimeRange) {
	v.value = val
	v.isSet = true
}

func (v NullableResolvableTimeRange) IsSet() bool {
	return v.isSet
}

func (v *NullableResolvableTimeRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolvableTimeRange(val *ResolvableTimeRange) *NullableResolvableTimeRange {
	return &NullableResolvableTimeRange{value: val, isSet: true}
}

func (v NullableResolvableTimeRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolvableTimeRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


