/*
Sumo Logic API

Go client for Sumo Logic API. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologic

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AzureEventHubPermissionErrorTracker type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AzureEventHubPermissionErrorTracker{}

// AzureEventHubPermissionErrorTracker struct for AzureEventHubPermissionErrorTracker
type AzureEventHubPermissionErrorTracker struct {
	TrackerIdentity
	// The specific reason of the permission error
	Reason *string `json:"reason,omitempty"`
}

type _AzureEventHubPermissionErrorTracker AzureEventHubPermissionErrorTracker

// NewAzureEventHubPermissionErrorTracker instantiates a new AzureEventHubPermissionErrorTracker object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureEventHubPermissionErrorTracker(trackerId string, error_ string, description string) *AzureEventHubPermissionErrorTracker {
	this := AzureEventHubPermissionErrorTracker{}
	this.TrackerId = trackerId
	this.Error = error_
	this.Description = description
	return &this
}

// NewAzureEventHubPermissionErrorTrackerWithDefaults instantiates a new AzureEventHubPermissionErrorTracker object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureEventHubPermissionErrorTrackerWithDefaults() *AzureEventHubPermissionErrorTracker {
	this := AzureEventHubPermissionErrorTracker{}
	return &this
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *AzureEventHubPermissionErrorTracker) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureEventHubPermissionErrorTracker) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *AzureEventHubPermissionErrorTracker) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *AzureEventHubPermissionErrorTracker) SetReason(v string) {
	o.Reason = &v
}

func (o AzureEventHubPermissionErrorTracker) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AzureEventHubPermissionErrorTracker) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedTrackerIdentity, errTrackerIdentity := json.Marshal(o.TrackerIdentity)
	if errTrackerIdentity != nil {
		return map[string]interface{}{}, errTrackerIdentity
	}
	errTrackerIdentity = json.Unmarshal([]byte(serializedTrackerIdentity), &toSerialize)
	if errTrackerIdentity != nil {
		return map[string]interface{}{}, errTrackerIdentity
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

func (o *AzureEventHubPermissionErrorTracker) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"trackerId",
		"error",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAzureEventHubPermissionErrorTracker := _AzureEventHubPermissionErrorTracker{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAzureEventHubPermissionErrorTracker)

	if err != nil {
		return err
	}

	*o = AzureEventHubPermissionErrorTracker(varAzureEventHubPermissionErrorTracker)

	return err
}

type NullableAzureEventHubPermissionErrorTracker struct {
	value *AzureEventHubPermissionErrorTracker
	isSet bool
}

func (v NullableAzureEventHubPermissionErrorTracker) Get() *AzureEventHubPermissionErrorTracker {
	return v.value
}

func (v *NullableAzureEventHubPermissionErrorTracker) Set(val *AzureEventHubPermissionErrorTracker) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureEventHubPermissionErrorTracker) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureEventHubPermissionErrorTracker) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureEventHubPermissionErrorTracker(val *AzureEventHubPermissionErrorTracker) *NullableAzureEventHubPermissionErrorTracker {
	return &NullableAzureEventHubPermissionErrorTracker{value: val, isSet: true}
}

func (v NullableAzureEventHubPermissionErrorTracker) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureEventHubPermissionErrorTracker) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


