/*
Sumo Logic API

Go client for Sumo Logic API. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologic

import (
	"encoding/json"
)

// checks if the CollectionS3AccessDeniedTrackerAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollectionS3AccessDeniedTrackerAllOf{}

// CollectionS3AccessDeniedTrackerAllOf struct for CollectionS3AccessDeniedTrackerAllOf
type CollectionS3AccessDeniedTrackerAllOf struct {
	// The bucket name of the associated Source.
	BucketName *string `json:"bucketName,omitempty"`
	// The access key used to make the request. In the case of IAM roles, this is the temporary key used for authentication.
	AccessKey *string `json:"accessKey,omitempty"`
}

// NewCollectionS3AccessDeniedTrackerAllOf instantiates a new CollectionS3AccessDeniedTrackerAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionS3AccessDeniedTrackerAllOf() *CollectionS3AccessDeniedTrackerAllOf {
	this := CollectionS3AccessDeniedTrackerAllOf{}
	return &this
}

// NewCollectionS3AccessDeniedTrackerAllOfWithDefaults instantiates a new CollectionS3AccessDeniedTrackerAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionS3AccessDeniedTrackerAllOfWithDefaults() *CollectionS3AccessDeniedTrackerAllOf {
	this := CollectionS3AccessDeniedTrackerAllOf{}
	return &this
}

// GetBucketName returns the BucketName field value if set, zero value otherwise.
func (o *CollectionS3AccessDeniedTrackerAllOf) GetBucketName() string {
	if o == nil || IsNil(o.BucketName) {
		var ret string
		return ret
	}
	return *o.BucketName
}

// GetBucketNameOk returns a tuple with the BucketName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionS3AccessDeniedTrackerAllOf) GetBucketNameOk() (*string, bool) {
	if o == nil || IsNil(o.BucketName) {
		return nil, false
	}
	return o.BucketName, true
}

// HasBucketName returns a boolean if a field has been set.
func (o *CollectionS3AccessDeniedTrackerAllOf) HasBucketName() bool {
	if o != nil && !IsNil(o.BucketName) {
		return true
	}

	return false
}

// SetBucketName gets a reference to the given string and assigns it to the BucketName field.
func (o *CollectionS3AccessDeniedTrackerAllOf) SetBucketName(v string) {
	o.BucketName = &v
}

// GetAccessKey returns the AccessKey field value if set, zero value otherwise.
func (o *CollectionS3AccessDeniedTrackerAllOf) GetAccessKey() string {
	if o == nil || IsNil(o.AccessKey) {
		var ret string
		return ret
	}
	return *o.AccessKey
}

// GetAccessKeyOk returns a tuple with the AccessKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionS3AccessDeniedTrackerAllOf) GetAccessKeyOk() (*string, bool) {
	if o == nil || IsNil(o.AccessKey) {
		return nil, false
	}
	return o.AccessKey, true
}

// HasAccessKey returns a boolean if a field has been set.
func (o *CollectionS3AccessDeniedTrackerAllOf) HasAccessKey() bool {
	if o != nil && !IsNil(o.AccessKey) {
		return true
	}

	return false
}

// SetAccessKey gets a reference to the given string and assigns it to the AccessKey field.
func (o *CollectionS3AccessDeniedTrackerAllOf) SetAccessKey(v string) {
	o.AccessKey = &v
}

func (o CollectionS3AccessDeniedTrackerAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollectionS3AccessDeniedTrackerAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BucketName) {
		toSerialize["bucketName"] = o.BucketName
	}
	if !IsNil(o.AccessKey) {
		toSerialize["accessKey"] = o.AccessKey
	}
	return toSerialize, nil
}

type NullableCollectionS3AccessDeniedTrackerAllOf struct {
	value *CollectionS3AccessDeniedTrackerAllOf
	isSet bool
}

func (v NullableCollectionS3AccessDeniedTrackerAllOf) Get() *CollectionS3AccessDeniedTrackerAllOf {
	return v.value
}

func (v *NullableCollectionS3AccessDeniedTrackerAllOf) Set(val *CollectionS3AccessDeniedTrackerAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionS3AccessDeniedTrackerAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionS3AccessDeniedTrackerAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionS3AccessDeniedTrackerAllOf(val *CollectionS3AccessDeniedTrackerAllOf) *NullableCollectionS3AccessDeniedTrackerAllOf {
	return &NullableCollectionS3AccessDeniedTrackerAllOf{value: val, isSet: true}
}

func (v NullableCollectionS3AccessDeniedTrackerAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionS3AccessDeniedTrackerAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


