/*
Sumo Logic API

Go client for Sumo Logic API. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologic

import (
	"encoding/json"
)

// checks if the SpansLimitItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpansLimitItem{}

// SpansLimitItem A representation of the limit operator which reduces the number of aggregate results returned:  either the top k results or bottom k results. 
type SpansLimitItem struct {
	// Describes whether the results should be sorted in an ascending or a descending order.
	Direction string `json:"direction"`
	// The number of aggregated results returned, e.g. if 10 is requested, then only the first 10 aggregated results are returned. 
	LimitValue int32 `json:"limitValue"`
}

// NewSpansLimitItem instantiates a new SpansLimitItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpansLimitItem(direction string, limitValue int32) *SpansLimitItem {
	this := SpansLimitItem{}
	this.Direction = direction
	this.LimitValue = limitValue
	return &this
}

// NewSpansLimitItemWithDefaults instantiates a new SpansLimitItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpansLimitItemWithDefaults() *SpansLimitItem {
	this := SpansLimitItem{}
	return &this
}

// GetDirection returns the Direction field value
func (o *SpansLimitItem) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *SpansLimitItem) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *SpansLimitItem) SetDirection(v string) {
	o.Direction = v
}

// GetLimitValue returns the LimitValue field value
func (o *SpansLimitItem) GetLimitValue() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LimitValue
}

// GetLimitValueOk returns a tuple with the LimitValue field value
// and a boolean to check if the value has been set.
func (o *SpansLimitItem) GetLimitValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LimitValue, true
}

// SetLimitValue sets field value
func (o *SpansLimitItem) SetLimitValue(v int32) {
	o.LimitValue = v
}

func (o SpansLimitItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpansLimitItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["direction"] = o.Direction
	toSerialize["limitValue"] = o.LimitValue
	return toSerialize, nil
}

type NullableSpansLimitItem struct {
	value *SpansLimitItem
	isSet bool
}

func (v NullableSpansLimitItem) Get() *SpansLimitItem {
	return v.value
}

func (v *NullableSpansLimitItem) Set(val *SpansLimitItem) {
	v.value = val
	v.isSet = true
}

func (v NullableSpansLimitItem) IsSet() bool {
	return v.isSet
}

func (v *NullableSpansLimitItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpansLimitItem(val *SpansLimitItem) *NullableSpansLimitItem {
	return &NullableSpansLimitItem{value: val, isSet: true}
}

func (v NullableSpansLimitItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpansLimitItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


