/*
Sumo Logic API

Go client for Sumo Logic API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologic

import (
	"encoding/json"
)

// AttributeValueReversedIndex struct for AttributeValueReversedIndex
type AttributeValueReversedIndex struct {
	// Value of the attribute.
	AttributeValue string `json:"attributeValue"`
	// List of span ids which have the given attribute and value.
	SpanIds []string `json:"spanIds"`
}

// NewAttributeValueReversedIndex instantiates a new AttributeValueReversedIndex object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttributeValueReversedIndex(attributeValue string, spanIds []string) *AttributeValueReversedIndex {
	this := AttributeValueReversedIndex{}
	this.AttributeValue = attributeValue
	this.SpanIds = spanIds
	return &this
}

// NewAttributeValueReversedIndexWithDefaults instantiates a new AttributeValueReversedIndex object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttributeValueReversedIndexWithDefaults() *AttributeValueReversedIndex {
	this := AttributeValueReversedIndex{}
	return &this
}

// GetAttributeValue returns the AttributeValue field value
func (o *AttributeValueReversedIndex) GetAttributeValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributeValue
}

// GetAttributeValueOk returns a tuple with the AttributeValue field value
// and a boolean to check if the value has been set.
func (o *AttributeValueReversedIndex) GetAttributeValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributeValue, true
}

// SetAttributeValue sets field value
func (o *AttributeValueReversedIndex) SetAttributeValue(v string) {
	o.AttributeValue = v
}

// GetSpanIds returns the SpanIds field value
func (o *AttributeValueReversedIndex) GetSpanIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SpanIds
}

// GetSpanIdsOk returns a tuple with the SpanIds field value
// and a boolean to check if the value has been set.
func (o *AttributeValueReversedIndex) GetSpanIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpanIds, true
}

// SetSpanIds sets field value
func (o *AttributeValueReversedIndex) SetSpanIds(v []string) {
	o.SpanIds = v
}

func (o AttributeValueReversedIndex) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["attributeValue"] = o.AttributeValue
	}
	if true {
		toSerialize["spanIds"] = o.SpanIds
	}
	return json.Marshal(toSerialize)
}

type NullableAttributeValueReversedIndex struct {
	value *AttributeValueReversedIndex
	isSet bool
}

func (v NullableAttributeValueReversedIndex) Get() *AttributeValueReversedIndex {
	return v.value
}

func (v *NullableAttributeValueReversedIndex) Set(val *AttributeValueReversedIndex) {
	v.value = val
	v.isSet = true
}

func (v NullableAttributeValueReversedIndex) IsSet() bool {
	return v.isSet
}

func (v *NullableAttributeValueReversedIndex) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttributeValueReversedIndex(val *AttributeValueReversedIndex) *NullableAttributeValueReversedIndex {
	return &NullableAttributeValueReversedIndex{value: val, isSet: true}
}

func (v NullableAttributeValueReversedIndex) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttributeValueReversedIndex) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


