/*
Sumo Logic API

Go client for Sumo Logic API. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologic

import (
	"encoding/json"
)

// checks if the GetViewFilterDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetViewFilterDefinition{}

// GetViewFilterDefinition struct for GetViewFilterDefinition
type GetViewFilterDefinition struct {
	// Name of the view. Help Doc:- (https://help.sumologic.com/docs/manage/partitions-data-tiers/)
	ViewName string `json:"viewName"`
}

// NewGetViewFilterDefinition instantiates a new GetViewFilterDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetViewFilterDefinition(viewName string) *GetViewFilterDefinition {
	this := GetViewFilterDefinition{}
	this.ViewName = viewName
	return &this
}

// NewGetViewFilterDefinitionWithDefaults instantiates a new GetViewFilterDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetViewFilterDefinitionWithDefaults() *GetViewFilterDefinition {
	this := GetViewFilterDefinition{}
	return &this
}

// GetViewName returns the ViewName field value
func (o *GetViewFilterDefinition) GetViewName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ViewName
}

// GetViewNameOk returns a tuple with the ViewName field value
// and a boolean to check if the value has been set.
func (o *GetViewFilterDefinition) GetViewNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ViewName, true
}

// SetViewName sets field value
func (o *GetViewFilterDefinition) SetViewName(v string) {
	o.ViewName = v
}

func (o GetViewFilterDefinition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetViewFilterDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["viewName"] = o.ViewName
	return toSerialize, nil
}

type NullableGetViewFilterDefinition struct {
	value *GetViewFilterDefinition
	isSet bool
}

func (v NullableGetViewFilterDefinition) Get() *GetViewFilterDefinition {
	return v.value
}

func (v *NullableGetViewFilterDefinition) Set(val *GetViewFilterDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableGetViewFilterDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableGetViewFilterDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetViewFilterDefinition(val *GetViewFilterDefinition) *NullableGetViewFilterDefinition {
	return &NullableGetViewFilterDefinition{value: val, isSet: true}
}

func (v NullableGetViewFilterDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetViewFilterDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


