/*
Sumo Logic API

Go client for Sumo Logic API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sumologic

import (
	"encoding/json"
)

// ListExtractionRulesResponse struct for ListExtractionRulesResponse
type ListExtractionRulesResponse struct {
	// List of field extraction rules.
	Data []ExtractionRule `json:"data"`
	// Next continuation token.
	Next *string `json:"next,omitempty"`
}

// NewListExtractionRulesResponse instantiates a new ListExtractionRulesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListExtractionRulesResponse(data []ExtractionRule) *ListExtractionRulesResponse {
	this := ListExtractionRulesResponse{}
	this.Data = data
	return &this
}

// NewListExtractionRulesResponseWithDefaults instantiates a new ListExtractionRulesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListExtractionRulesResponseWithDefaults() *ListExtractionRulesResponse {
	this := ListExtractionRulesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ListExtractionRulesResponse) GetData() []ExtractionRule {
	if o == nil {
		var ret []ExtractionRule
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListExtractionRulesResponse) GetDataOk() ([]ExtractionRule, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListExtractionRulesResponse) SetData(v []ExtractionRule) {
	o.Data = v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *ListExtractionRulesResponse) GetNext() string {
	if o == nil || o.Next == nil {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListExtractionRulesResponse) GetNextOk() (*string, bool) {
	if o == nil || o.Next == nil {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *ListExtractionRulesResponse) HasNext() bool {
	if o != nil && o.Next != nil {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *ListExtractionRulesResponse) SetNext(v string) {
	o.Next = &v
}

func (o ListExtractionRulesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if o.Next != nil {
		toSerialize["next"] = o.Next
	}
	return json.Marshal(toSerialize)
}

type NullableListExtractionRulesResponse struct {
	value *ListExtractionRulesResponse
	isSet bool
}

func (v NullableListExtractionRulesResponse) Get() *ListExtractionRulesResponse {
	return v.value
}

func (v *NullableListExtractionRulesResponse) Set(val *ListExtractionRulesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListExtractionRulesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListExtractionRulesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListExtractionRulesResponse(val *ListExtractionRulesResponse) *NullableListExtractionRulesResponse {
	return &NullableListExtractionRulesResponse{value: val, isSet: true}
}

func (v NullableListExtractionRulesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListExtractionRulesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


